package com.globalaccelerex.globalaccelerexandroidposclientlibrary.util

object GaResponseKeys {
    const val PARAMETERS_REQUEST_CODE = 1001
    const val KEY_EXCHANGE_REQUEST_CODE = 1002
    const val CARD_PURCHASE_REQUEST_CODE = 1003
    const val CARD_PURCHASE_WITH_CB_REQUEST_CODE = 1004
    const val MOBILE_MONEY_PURCHASE_REQUEST_CODE = 1005
    const val MOBILE_MONEY_STATUS_CHECK_REQUEST_CODE = 1006
    const val CNP_PURCHASE_REQUEST_CODE = 1007
    const val CNP_PURCHASE_WITH_CB_REQUEST_CODE = 1008
    const val CNP_PRE_AUTH_PURCHASE_REQUEST_CODE = 1009
    const val CNP_PRE_AUTH_COMPLETION_REQUEST_CODE = 1010
    const val CNP_CARD_BALANCE_REQUEST_CODE = 1011
    const val CNP_REFUND_REQUEST_CODE = 1012
}